---
title: "Output_play"
output: html_document
date: "2024-03-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Checking results of each output sampler
playing with each output samplers

packages
```{r}
library(ggplot2)
library(ggthemes)
library(dplyr)
```


### saved outputs
```{r}
# output_growth # = output from growth model
# output_cal # = output from calibration sampler
# output_inde # = output from independent sampler
# output_nodec # = output from nondecreasing sampler
```

## Variance and bias assessment
Compare sampler variance and bias
```{r}
# variance dataframe
var_all <- rbind(
  output_cal$summaries$altimeters %>% filter(parameter == 'variance') %>% mutate(sampler = "calibration"),
  output_inde$summaries$altimeters %>% filter(parameter == 'variance') %>% mutate(sampler = "independent"),
  output_nodec$summaries$altimeters %>% filter(parameter == 'variance') %>% mutate(sampler = "nondecreasing"),
  output_growth$summaries$altimeters %>% filter(parameter == 'variance') %>% mutate(sampler = "growth"))

# bias dataframe
bias_all <- rbind(
  output_cal$summaries$altimeters %>% filter(parameter == 'bias') %>% mutate(sampler = "calibration"),
  output_inde$summaries$altimeters %>% filter(parameter == 'bias') %>% mutate(sampler = "independent"),
  output_nodec$summaries$altimeters %>% filter(parameter == 'bias') %>% mutate(sampler = "nondecreasing"),
  output_growth$summaries$altimeters %>% filter(parameter == 'bias') %>% mutate(sampler = "growth"))


## plot 
var_all %>% #filter(sampler != "calibration") %>% 
  filter(!(UAS == "P4P" & altimeter == "Laser")) %>%
  ggplot() + theme_bw() +
  geom_pointrange(aes(x = sampler, y = mean, ymin = lower, ymax = upper, color = sampler, shape = altimeter), position = "jitter") + facet_wrap(~UAS) + scale_x_discrete(guide = guide_axis(angle = -30)) + ylab("variance") + 
  scale_color_manual(name = "samplers", breaks = c('calibration', 'growth', 'independent', 'nondecreasing'),
                       values = c('calibration' = "purple", 'growth' = "darkorange", 'independent' = "lightblue",
                                  'nondecreasing' = "darkred"))



bias_all %>% filter(!(UAS == "P4P" & altimeter == "Laser")) %>% ggplot() + theme_bw() +
  geom_pointrange(aes(x = sampler, y = mean, ymin = lower, ymax = upper, color = sampler, shape = altimeter), position = "jitter") + facet_wrap(~UAS) + scale_x_discrete(guide = guide_axis(angle = -30)) + ylab("bias")
  

```


## Compare sampler output

```{r}
# arrange the whales data frame by whales with the most repeated samples
top_n_whales <- unique(whales %>%  group_by(whale_ID) %>% summarise(ns = n(), Age, AgeType) %>% arrange(desc(ns)) %>% filter(Age == max(Age)))

# make a list of the top 10 whales with repeated samples
whale_list <- as.list(top_n_whales$whale_ID)[1:10]

# create a loop to create a plot of these 10 whales comparing each ouput from the sampler
for (i in whale_list){
  whale_X = i
  
  # plot each whale
  plot_mx <- ggplot() + 
  theme_few() + 
  geom_pointrange(data = output_growth$summaries$objects %>% 
  filter(Subject == whale_X), aes(x = as.numeric(Timepoint), y = mean, ymin = lower, ymax = upper, color = "growth")) +
  geom_line(data = output_growth$summaries$objects %>% 
  filter(Subject == whale_X), aes(x = as.numeric(Timepoint), y = mean, color = "growth")) + 
  
  geom_pointrange(data = output_inde$summaries$objects %>% 
  filter(Subject == whale_X), aes(x = as.numeric(Timepoint), y = mean, ymin = lower, ymax = upper, color = "independent")) + 
  geom_line(data = output_inde$summaries$objects %>% 
  filter(Subject == whale_X), aes(x = as.numeric(Timepoint), y = mean, color = "independent")) +
  
  geom_pointrange(data = output_nodec$summaries$objects %>% 
  filter(Subject == whale_X), aes(x = as.numeric(Timepoint), y = mean, ymin = lower, ymax = upper, color = "nondecreasing")) + 
  geom_line(data = output_nodec$summaries$objects %>% 
  filter(Subject == whale_X), aes(x = as.numeric(Timepoint), y = mean, color = "nondecreasing")) + 
  ylab("TL (m)") +
  ggtitle(paste("whale ID = ", whale_X, ", latest age = ", 
                top_n_whales$Age[top_n_whales$whale_ID == whale_X], sep = "")) +
    scale_color_manual(name = "samplers", breaks = c('growth', 'independent', 'nondecreasing'),
                       values = c('growth' = "darkorange", 'independent' = "lightblue", 'nondecreasing' = "darkred"))
  print(plot_mx)
}

```
           
           

```{r}
output_growth$summaries$objects %>% 
  filter(Subject == '196') %>% 
  ggplot(aes(x = as.numeric(Timepoint), y = mean, ymin = lower, ymax = upper)) + 
  geom_line() + 
  geom_pointrange() + 
  theme_few()
```

